### ISSUE TITLE
Получение состояния кнопки на клавиатуре

### ISSUE THREAD

**Issue by avdeevx** [xxDark/cristalix-client-api-java#10]
> Мне нужно получить состояние кнопки (нажата она или нет) в данный момент, но сделать это не представляется возможным.

- Существует ивент **_KeyPress_**  `dev.xdark.clientapi.event.input.KeyPress`. С его помощью можно получить момент когда кнопка нажата, но ивента на событие отпускания кнопки нет.

- Существует класс **_KeyboardHelper_** `dev.xdark.clientapi.input.KeyboardHelper`. Он обладает методами получения состояния некоторых кнопок (Shift, Alt, и т.д.), но методов получения состояния конкретной кнопки нет.

**Comment by nartsisss** [comment]
http://legacy.lwjgl.org/javadoc/org/lwjgl/input/Keyboard.html#isKeyDown(int)

Чем не устраивает?

**Comment by MineLGBT** [comment]
> Чем не устраивает?

Вот этим https://github.com/xxDark/cristalix-client-api-java/issues/9
