### ISSUE TITLE
Получение здоровья игрока

### ISSUE THREAD

**Issue by avdeevx** [xxDark/cristalix-client-api-java#8]
Возможно ли получить здоровье игрока без доступа к _server side_?
Получить, например xp или сытость игрока возможно, а для здоровья подобного не нашёл.

**Comment by nartsisss** [comment]
Нельзя
![image](https://user-images.githubusercontent.com/54633007/128214345-176a28ca-47ea-481d-be41-bd200b3678e0.png)

**Comment by xxDark** [comment]
Добавлю, как будет обновление.
